=== Pankaj2147223/VehicleParts/XSD_File_CAT.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Company">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Employee">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Emp-name" type="xs:string" />
              <xs:element name="Emp-age" type="xs:integer" />
              <xs:element name="Emp-salary" type="xs:long" />
              <xs:element name="Emp-emailid" type="xs:string" />
              <xs:element name="Emp-phonenum" type="xs:unsignedLong" />
              <xs:element name="Emp-designation" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:unsignedByte" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Employee">
      <xs:complexType>
        <xs:sequence>
            <xs:element name="Emp-salary">
                <xs:simpleType>
                    <xs:restriction base="xs:long">
                        <xs:minInclusive value="50000"/>
                        <xs:maxInclusive value="200000"/>
                    </xs:restriction>
                </xs:simpleType>

            </xs:element>
        </xs:sequence>
      </xs:complexType>
  </xs:element>
</xs:schema>

=== Pankaj2147223/VehicleParts/XML_File_CAT.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="XSL_File_CAT.xsl"?>

<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="XSD_File_CAT.xsd">

<Employee id="1">    
    <Emp-name>Pankaj</Emp-name>
    <Emp-age>22</Emp-age>
    <Emp-salary>125000</Emp-salary>
    <Emp-emailid>pankaj.s@gmail.com</Emp-emailid>
    <Emp-phonenum>9876543210</Emp-phonenum>
    <Emp-designation>Developer</Emp-designation>
</Employee>

<Employee id="2">    
    <Emp-name>Ritish</Emp-name>
    <Emp-age>21</Emp-age>
    <Emp-salary>70000</Emp-salary>
    <Emp-emailid>ritish.s@gmail.com</Emp-emailid>
    <Emp-phonenum>9876023210</Emp-phonenum>
    <Emp-designation>Tester</Emp-designation>
</Employee>

<Employee id="3">    
    <Emp-name>Jain</Emp-name>
    <Emp-age>61</Emp-age>
    <Emp-salary>1200</Emp-salary>
    <Emp-emailid>jain.s@gmail.com</Emp-emailid>
    <Emp-phonenum>9826023210</Emp-phonenum>
    <Emp-designation>Supervisor</Emp-designation>
</Employee>

<Employee id="4">    
    <Emp-name>Sunaina</Emp-name>
    <Emp-age>42</Emp-age>
    <Emp-salary>192000</Emp-salary>
    <Emp-emailid>s.s@gmail.com</Emp-emailid>
    <Emp-phonenum>9876023243</Emp-phonenum>
    <Emp-designation>Marketer</Emp-designation>
</Employee>

<Employee id="5">    
    <Emp-name>Sam</Emp-name>
    <Emp-age>32</Emp-age>
    <Emp-salary>182000</Emp-salary>
    <Emp-emailid>sam.s@gmail.com</Emp-emailid>
    <Emp-phonenum>9878093210</Emp-phonenum>
    <Emp-designation>Associate Project Manager</Emp-designation>
</Employee>

</Company>
